name = "navsphere"
compatibility_date = "2024-11-11"
compatibility_flags = ["nodejs_compat"]
pages_build_output_dir = ".vercel/output/static"

[env.production.vars]
GITHUB_ID = "Ov23liIu2gokXVzCIBe2"
GITHUB_OWNER = "908203"
GITHUB_REPO = "Mainpage"
GITHUB_BRANCH = "main"
NEXTAUTH_URL = "https://page.908203.xyz/api/auth"
NEXT_PUBLIC_API_URL="https://page.908203.xyz/"

